### ISSUE TITLE
Can the shape of output image be set to any size?

### ISSUE THREAD

**Issue by trikim** [leongatys/DeepTextures#11]
In the code, the size of the output image is the same to the input image. Can the shape of the output image be set to any size? if can, how to realize?

**Comment by leongatys** [comment]
In principle it is possible. But since the CNN activations change with image size due to boundary effects from 0 padding, the quality of the results is typically decreased. 
Thus, to generate large textures from small source images, I would recommend to generate multiple small ones. You could always initialize part of the boundary region with a previously generated texture patch so that you don't get seams at the boundary. 

Hope that helps, 
Leon
